services:
  - type: web
    name: topbestgames-api
    env: node
    region: oregon  # Choose the region closest to your users
    plan: free  # Use free plan
    buildCommand: npm ci --omit=dev
    startCommand: node server.js
    # These environment variables will be set automatically for your service
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: "https://your-frontend-url-here.com"  # Change this to your frontend URL when you deploy it
      - key: DATABASE_URL
        fromDatabase:
          name: topbestgames-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    # Configure health check for Render
    healthCheckPath: /health
    healthCheckTimeout: 10000
    # Auto-deploy on changes to the main branch
    autoDeploy: true
    # Ensure the service is publicly accessible
    public: true

databases:
  - name: topbestgames-db
    databaseName: topbestgames
    user: topbestgames_user